version: '3'
services:
  compense-postgresql:
    image: postgres:15.1
    volumes:
      - compense_db:/var/lib/postgresql
      - compense_data:/var/lib/postgresql/data
    networks:
      - back
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5462:5432

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    depends_on:
      - compense-postgresql
    networks:
      - back

  cloud-config-server:
    image: dthibau/cloud-config:3.2.2
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://gitlab.com/sdi-poc/sica-microservices/config.git
    ports:
      - 8888:8888

  eureka:
    image: dthibau/eureka:3.2.2
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://cloud-config-server:8888
      - SPRING_CLOUD_CONFIG_FAILFAST=true
    ports:
      - "1111:1111"
    depends_on:
      - cloud-config-server
    restart: on-failure

  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

  redpanda:
    image : docker.redpanda.com/redpandadata/console:latest
    ports:
      - 8079:8080
    environment:
      - KAFKA_BROKERS=kafka:9092

#  poc-banque:
#    image: dthibau/poc-banque:0.0.1
#    environment:
#      - SPRING_CLOUD_CONFIG_URI=http://cloud-config-server:8888
#      - SPRING_CLOUD_CONFIG_FAILFAST=true
#    ports:
#      - "8091:8083"
#    depends_on:
#      - cloud-config-server
#    restart: on-failure
    
volumes:
  compense_data:
  compense_db:
  kafka_data:
    driver: local

networks:
  back:



