version: '3.3'

services:
  cloud-config-server:
    image: dthibau/cloud-config:3.2.2
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://gitlab.com/sdi-poc/sica-microservices/config.git
    ports:
      - 8888:8888

  eureka:
    image: dthibau/eureka:3.2.2
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://cloud-config-server:8888
      - SPRING_CLOUD_CONFIG_FAILFAST=true
    ports:
      - "1111:1111"
    depends_on:
      - cloud-config-server
    restart: on-failure
