
INSERT INTO COMPTE_REGLEMENT(SOLDE,ETAT_COMPTE,LIBELLE,REFERENCE) VALUES(130000.00,'BROUILLON','Compte de traitement','Z00_124AE');
INSERT INTO COMPTE_REGLEMENT(SOLDE,ETAT_COMPTE,LIBELLE,REFERENCE) VALUES(98222.00,'BROUILLON','Compte de dépenses','C00_78YO');

INSERT INTO BANQUE(FK_ID_COMPTE,CODE_BANQUE,ETAT_BANQUE,LIBELLE,PAYS_CODE_ISO,PAYS_LIBELLE) VALUES(1,'AA_1242_I','BROUILLON','BANQUE ATLANTIQUE','CI','Cote d Ivoire');
INSERT INTO BANQUE(FK_ID_COMPTE,CODE_BANQUE,ETAT_BANQUE,LIBELLE,PAYS_CODE_ISO,PAYS_LIBELLE) VALUES(2,'BB_3455KID','BROUILLON','BANK OF AFRICA MALI','SN','Sénégal');

