INSERT INTO SOLDE_COMPENSATION (NU_JOURNEECOMPENSATION_FK, DA_DATEOPERATION, CH_BANQUE_FK, NU_SOLDE, CH_ETAT) VALUES (1, '2024-03-25', 'CBAO', 395000, 'ACTIF'); 
INSERT INTO SOLDE_COMPENSATION (NU_JOURNEECOMPENSATION_FK, DA_DATEOPERATION, CH_BANQUE_FK, NU_SOLDE, CH_ETAT) VALUES (2, '2024-03-26', 'SGBS', 90000, 'ACTIF');
INSERT INTO SOLDE_COMPENSATION (NU_JOURNEECOMPENSATION_FK, DA_DATEOPERATION, CH_BANQUE_FK, NU_SOLDE, CH_ETAT) VALUES (3, '2024-03-27', 'BICIS', 6000, 'ACTIF');
INSERT INTO SOLDE_COMPENSATION (NU_JOURNEECOMPENSATION_FK, DA_DATEOPERATION, CH_BANQUE_FK, NU_SOLDE, CH_ETAT) VALUES (4, '2024-03-28', 'BOA', 7000, 'ACTIF');
INSERT INTO SOLDE_COMPENSATION (NU_JOURNEECOMPENSATION_FK, DA_DATEOPERATION, CH_BANQUE_FK, NU_SOLDE, CH_ETAT) VALUES (5, '2024-03-29', 'BHS', 100000, 'ACTIF');
INSERT INTO SOLDE_COMPENSATION (NU_JOURNEECOMPENSATION_FK, DA_DATEOPERATION, CH_BANQUE_FK, NU_SOLDE, CH_ETAT) VALUES (6, '2024-03-30', 'UBA', 45000, 'ACTIF');
INSERT INTO SOLDE_COMPENSATION (NU_JOURNEECOMPENSATION_FK, DA_DATEOPERATION, CH_BANQUE_FK, NU_SOLDE, CH_ETAT,TYPE_OPERATION) VALUES (7, '2024-03-25', 'CBAO', 25000, 'ACTIF','015');
INSERT INTO SOLDE_COMPENSATION (NU_JOURNEECOMPENSATION_FK, DA_DATEOPERATION, CH_BANQUE_FK, NU_SOLDE, CH_ETAT,TYPE_OPERATION) VALUES (8, '2024-03-29', 'BHS', 25000, 'ACTIF','015');

