spring :
  application:
    name: reglement
    
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:reglement
  
server:
  port: 8083

keycloak:
  realm: poc
  auth-server-url: http://localhost:8180
  client-id: reglement
  client-secret: "secret"
  
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  
---    
 spring:
  config:
    activate:
      on-profile: integration
  r2dbc:
      url: r2dbc:postgresql://reglement-postgresql:5432/reglement_db
      username: postgres
      password: postgres
      initialization-mode: never
  data:
      r2dbc:
        initialization-mode: never
 logging:
   level:
     org:
       springframework:
         security: DEBUG
     reactor:
       netty:
         http:
           client: DEBUG

 keycloak:
   auth-server-url: http://keycloak:8180